# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0vl9lwNb9ZgvPgXNDru7zWO4QZiOAgo
"""

import tkinter as tk
from tkinter import filedialog, messagebox

# ---------------------- Functions ---------------------- #

def analyze_text():
    """Counts words, characters, and lines in the text box."""
    text = entry.get("1.0", "end-1c")
    words = len(text.split())
    chars = len(text)
    lines = text.count("\n") + 1 if text else 0
    result_label.config(
        text=f"Words: {words} | Characters: {chars} | Lines: {lines}"
    )

def clear_text():
    """Clears the text area and result label."""
    entry.delete("1.0", "end")
    result_label.config(text="")

def save_results():
    """Saves the analysis results and text to a chosen file."""
    text = entry.get("1.0", "end-1c")
    if not text.strip():
        messagebox.showwarning("Warning", "Text box is empty!")
        return

    words = len(text.split())
    chars = len(text)
    lines = text.count("\n") + 1

    file = filedialog.asksaveasfilename(
        defaultextension=".txt",
        filetypes=[("Text Files", "*.txt")]
    )

    if file:
        try:
            with open(file, "w", encoding="utf-8") as f:
                f.write("Text Analysis Report\n")
                f.write("====================\n")
                f.write(f"Words: {words}\nCharacters: {chars}\nLines: {lines}\n\n")
                f.write("Original Text:\n")
                f.write(text)

            messagebox.showinfo("Saved", "Results saved successfully!")
        except Exception as e:
            messagebox.showerror("Error", str(e))

def open_file():
    """Opens a .txt file and loads its content into the text box.
    Tries multiple encodings to avoid UnicodeDecodeError."""
    file = filedialog.askopenfilename(
        filetypes=[("Text Files", "*.txt"), ("All Files", "*.*")]
    )

    if not file:
        return

    content = None
    encodings_to_try = ["utf-8", "cp1252", "latin-1"]

    for enc in encodings_to_try:
        try:
            with open(file, "r", encoding=enc) as f:
                content = f.read()
            break  # success
        except UnicodeDecodeError:
            continue

    if content is None:
        messagebox.showerror(
            "Error",
            "Unable to read this file.\nUnsupported text encoding."
        )
        return

    entry.delete("1.0", "end")
    entry.insert("1.0", content)

def exit_app():
    """Closes the app."""
    root.destroy()

# ---------------------- GUI Setup ---------------------- #

root = tk.Tk()
root.title("Advanced Mini Text Analyzer")
root.geometry("500x400")

# Menu Bar
menu_bar = tk.Menu(root)
file_menu = tk.Menu(menu_bar, tearoff=0)
file_menu.add_command(label="Open", command=open_file)
file_menu.add_command(label="Save Results", command=save_results)
file_menu.add_separator()
file_menu.add_command(label="Exit", command=exit_app)
menu_bar.add_cascade(label="File", menu=file_menu)

help_menu = tk.Menu(menu_bar, tearoff=0)
help_menu.add_command(label="About", command=lambda: messagebox.showinfo(
    "About", "Mini Text Analyzer v1.0\nCreated with Tkinter by Yasser"))
menu_bar.add_cascade(label="Help", menu=help_menu)

root.config(menu=menu_bar)

# Label
tk.Label(root, text="Enter or open a text file to analyze:", font=("Arial", 11)).pack(pady=8)

# Text Box
entry = tk.Text(root, height=10, width=55)
entry.pack(pady=5)

# Buttons Frame
btn_frame = tk.Frame(root)
btn_frame.pack(pady=10)

tk.Button(btn_frame, text="Analyze", width=12, command=analyze_text).grid(row=0, column=0, padx=5)
tk.Button(btn_frame, text="Clear", width=12, command=clear_text).grid(row=0, column=1, padx=5)
tk.Button(btn_frame, text="Save", width=12, command=save_results).grid(row=0, column=2, padx=5)

# Result Label
result_label = tk.Label(root, text="", font=("Arial", 11, "bold"))
result_label.pack(pady=10)

root.mainloop()